version: '3.8'

services:
  backend:
    build:
      context: ./backend # Path to your API's Dockerfile and source code
      dockerfile: Dockerfile
    restart: always # Restart the container if it crashes
    ports:
      - '5500:5500' # Map host port 5500 to container port 5500
    volumes:
      - ./backend:/app # Mount the API's source code into the container
    depends_on:
      - posgres
    environment:
      DATABASE_URL: postgresql://postgres:root@localhost:5432/odoClone?schema=public # Connection string for your API

  posgres:
    image: postgres:17-alpine # Use a specific PostgreSQL image version
    restart: always # Restart the container if it crashes
    ports:
      - '5432:5432' # Map host port 5432 to container port 5432
    environment:
      POSTGRES_DB: odoClone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data # Persist database data
