export const ErrorCodeEnum = {
  ACCESS_UNAUTHORIZED: 'ACCESS_UNAUTHORIZED',

  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_USER_ALREADY_EXISTS: 'AUTH_USER_ALREADY_EXISTS',

  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_NOT_FOUND: 'AUTH_TOKEN_NOT_FOUND',
  AUTH_NOT_FOUND: 'AUTH_NOT_FOUND',
  AUTH_TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_UNAUTHORIZED_ACCESS: 'AUTH_UNAUTHORIZED_ACCESS',

  //Facture errors
  FACTURE_NOT_FOUND: 'FACTURE_NOT_FOUND',

  //Devis errors
  DEVIS_NOT_FOUND: 'DEVIS_NOT_FOUND',

  //Access Control Errors

  //Validation and Resource Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',

  //Systeme Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};
